Move user to context block
cds-hooks/sandbox pull request #61
Opened 2018-09-29 04:48 UTC by kolkheang

Per https://github.com/cds-hooks/docs/issues/232, moving user to the context block

2018-09-29 11:34 UTC, kpshek requested changes
Thanks @kolkheang. Can you add the `user` back to the top-level request so that we can ease developers into this change? Since cds-hooks/docs/issues/232 hasn't yet been applied to the spec, there are likely people who don't know this change is coming. By keeping user at the top-level, but also including it in the context, will allow things to stay working for everyone.

I'll see if we can get the spec change applied this weekend and then perhaps at the end/after the Connectathon we can remove user from the top-level request field.

2018-09-29 11:34 UTC, kpshek requested changes

2018-09-29 11:34 UTC, kpshek commented on src/retrieve-data-helpers/service-exchange.js
> -    user,
This is the line that I'm saying we simply put back.

2018-09-29 12:02 UTC, kolkheang commented
👍 
That's a good plan.  Thanks @kpshek !

2018-09-30 11:54 UTC, kpshek approved these changes

2018-09-30 11:54 UTC, merged