Rename hard-stop to critical per the 1.0 specification
cds-hooks/sandbox pull request #64
Opened 2018-10-11 18:23 UTC by mgrowette

updated `hard-stop` indicator to `critical` per the CDS Hooks Spec

2018-10-11 20:03 UTC, kolkheang approved these changes
@migrow Thanks for the contribution! Can you add a link to the spec or ballot for this change?

2018-10-11 20:07 UTC, migrow commented
Sure thing!

'Urgency/importance of what this card conveys. Allowed values, in order of increasing urgency, are: info, warning, critical. The EHR MAY use this field to help make UI display decisions such as sort order or coloring.'
https://cds-hooks.org/specification/1.0/#card-attributes

2018-10-12 10:30 UTC, kpshek requested changes
Thanks so much for this contribution @migrow!

One change you missed was in `card-list.css`.  There is an `.alert-hard-stop` CSS class that needs to be renamed to `.alert-critical`.  The following line in `card-list.jsx` applies the CSS class based upon the card's indicator:

```js
const classes = cx(styles['decision-card'], styles.alert, styles[`alert-${card.indicator}`]);
```

2018-10-12 10:30 UTC, kpshek commented on src/components/CardList/card-list.jsx
> +      'critical': 2,
Can you remove the single quotes around `'critical'`? They were needed when this was `hard-stop` (due to the dash), but now we can remove them which puts it inline with the other indicator values.

2018-10-12 10:30 UTC, kpshek commented on src/components/CardList/card-list.jsx
> +      'critical': '#c00',
Same comment above regarding the single quotes

2018-10-12 13:24 UTC, kpshek approved these changes
Thanks @migrow!

2018-10-12 13:25 UTC, merged